name: Check Google Drive File

on:
  schedule:
    - cron: '*/6 * * * *' # Runs every hour on the hour, to disable, change to 1 1 *

jobs:
  update_md_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace '3.x' with your desired Python version
          
      - name: Install Dependencies
        run: |
          pip install pandas
          
      - name: Commit and Push Changes
        run: |
          wget https://raw.githubusercontent.com/2010johnlee/2010johnlee.github.io/main/temp.md
          var3=$(python check_time.py)
          if ! cmp -s xiv.md temp.md; then
            mv temp.md xiv.md
            git config user.name "ECCRedM-Media"
            git config user.email "ECCRedM-Media@gmail.com"
            git add xiv.md
            git commit -m "Update xiv.md"  # Use -m to provide a commit message
            IFS=',' read -r var1 var2 < "xiv.md" #var1 is title, var2 is url, var3 is partial path
            echo $var1
            echo $var2
            echo $var3
            echo ${var3#sharing/2022/wk*/}.m4a
            wget -o ${var3#sharing/2022/wk*/}.m4a $var2
            if [ -e media/$var3.m4a ]; then
              echo "File already exists." >> log.md
              TZ="America/Los_Angeles" date >> log.md
              git config user.name "ECCRedM-Media"
              git config user.email "ECCRedM-Media@gmail.com"
              git add log.md
              git commit -m "Update log.md"  # Use -m to provide a commit message
              git push
            else
              mv ${var3#sharing/2022/wk*/}.m4a media/$var3.m4a
              echo "File updated." >> log.md
              TZ="America/Los_Angeles" date >> log.md
              git config user.name "ECCRedM-Media"
              git config user.email "ECCRedM-Media@gmail.com"
              git add media/$var3.m4a  # Stage the changes
              git commit -m "Update media/$var3.m4a"  # Use -m to provide a commit message
              git add log.md
              git commit -m "Update log.md"  # Use -m to provide a commit message
              git push
           fi
          fi

